/* Generated by Yosys 0.20+70 (git sha1 6e907acf86d, gcc 8.3.1 -fPIC -Os) */

module iiitb_bc(Clk, reset, UpOrDown, Count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input Clk;
  wire Clk;
  output [3:0] Count;
  wire [3:0] Count;
  input UpOrDown;
  wire UpOrDown;
  input reset;
  wire reset;
  sky130_fd_sc_hd__inv_2 _18_ (
    .A(Count[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_2 _19_ (
    .A(Count[0]),
    .B(Count[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__or2_2 _20_ (
    .A(Count[0]),
    .B(Count[1]),
    .X(_09_)
  );
  sky130_fd_sc_hd__a21oi_2 _21_ (
    .A1(_08_),
    .A2(_09_),
    .B1(UpOrDown),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and3_2 _22_ (
    .A(UpOrDown),
    .B(_08_),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__or2_2 _23_ (
    .A(_10_),
    .B(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__buf_1 _24_ (
    .A(_12_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand3_2 _25_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(Count[2]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a21o_2 _26_ (
    .A1(Count[0]),
    .A2(Count[1]),
    .B1(Count[2]),
    .X(_14_)
  );
  sky130_fd_sc_hd__nand2_2 _27_ (
    .A(_13_),
    .B(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_2 _28_ (
    .A(_10_),
    .B(_15_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__or3_2 _29_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(Count[2]),
    .X(_16_)
  );
  sky130_fd_sc_hd__mux2_2 _30_ (
    .A0(_16_),
    .A1(_13_),
    .S(UpOrDown),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_2 _31_ (
    .A(Count[3]),
    .B(_17_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__inv_2 _32_ (
    .A(reset),
    .Y(_04_)
  );
  sky130_fd_sc_hd__inv_2 _33_ (
    .A(reset),
    .Y(_05_)
  );
  sky130_fd_sc_hd__inv_2 _34_ (
    .A(reset),
    .Y(_06_)
  );
  sky130_fd_sc_hd__inv_2 _35_ (
    .A(reset),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_2 _36_ (
    .CLK(Clk),
    .D(_00_),
    .Q(Count[0]),
    .RESET_B(_04_)
  );
  sky130_fd_sc_hd__dfrtp_2 _37_ (
    .CLK(Clk),
    .D(_01_),
    .Q(Count[1]),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_2 _38_ (
    .CLK(Clk),
    .D(_02_),
    .Q(Count[2]),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_2 _39_ (
    .CLK(Clk),
    .D(_03_),
    .Q(Count[3]),
    .RESET_B(_07_)
  );
endmodule
